NET_MAIN = "main"
NET_DEV = "dev"
NET_TEST = "test"

NETS = (NET_MAIN, NET_TEST, NET_DEV)
MASTERADDR_NETBYTES = (0x21, 53, 24)
SUBADDR_NETBYTES = (42, 63, 36)
INTADDRR_NETBYTES = (19, 54, 25)

PRIO_UNIMPORTANT = 1
PRIO_NORMAL = 2
PRIO_ELEVATED = 3
PRIO_PRIORITY = 4
PRIO_FLASH = 5